### ISSUE TITLE
如何默认优先127.0.0.1的地址

### ISSUE THREAD

**Issue by markzhou537** [pugwoo/hessoa#2]
如图，主机拥有外网网卡
![image](https://user-images.githubusercontent.com/15846359/39136811-a72f34c0-474e-11e8-9ad2-9b613a7f1670.png)
hessoa配置是优先使用内网地址，可是只扫描了外网网卡的地址到redis注册中心，这样会不会造成SOAClient调用服务过慢？

**Comment by markzhou537** [comment]
@pugwoo

**Comment by pugwoo** [comment]
127.0.0.1每台机器都有，实际上无法作为判断是否是本机的依据，所以127.0.0.1难以作为ip地址存放到redis中。SOA的实际场景是分布式，127.0.0.1的加入实际上会对配置中心的性能造成干扰。

阿里云和腾讯云都有内网ip，建议从怎样搞出内网ip为方向解决问题，这是最好的解决方案。

另外，hessoa支持类似`/etc/hosts`的做法，指定对应类的服务地址，详见：`SOAClient`类注释文档说明。这个功能应该可以满足你特别指定127.0.0.1。

**Comment by markzhou537** [comment]
@pugwoo ok，我试试
